// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psmtiawvmhwwcqfvecwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzbXRpYXd2bWh3d2NxZnZlY3diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDc4OTcsImV4cCI6MjA2MzY4Mzg5N30.csdbss8oOO510YbOlT1br38C7dUEjSIvv2YhjbQjgTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);